/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        /** Delete Campaign */
        delete: operations["delete_campaign_api_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Campaign
         * @description Правка названия, темы и текста. Только пока письма никто не получил.
         */
        patch: operations["update_campaign_api_campaigns__campaign_id__patch"];
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipients */
        get: operations["list_recipients_api_campaigns__campaign_id__recipients_get"];
        put?: never;
        /** Add Recipients */
        post: operations["add_recipients_api_campaigns__campaign_id__recipients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Recipients Import */
        post: operations["preview_recipients_import_api_campaigns__campaign_id__recipients_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/recipients/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Recipients */
        post: operations["import_recipients_api_campaigns__campaign_id__recipients_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/configs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Configs
         * @description Ставит в очередь недостающие конфиги — генерацию делает фоновый воркер.
         *
         *     Без тела (или с пустым `servers`) берутся все серверы рассылки — это кнопка
         *     «Сгенерировать все». Со списком — только перечисленные, по кнопке отдельного
         *     сервера.
         */
        post: operations["generate_configs_api_campaigns__campaign_id__configs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Campaign */
        post: operations["start_campaign_api_campaigns__campaign_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Failed
         * @description Возвращает упавших получателей в очередь и открывает кампанию для повтора.
         *
         *     Статус кампании при этом сбрасывается в NEW, а не запускается отправка сразу:
         *     решение «слать снова» остаётся за человеком, кнопкой, как и первый запуск.
         */
        post: operations["retry_failed_api_campaigns__campaign_id__retry_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Campaign */
        post: operations["stop_campaign_api_campaigns__campaign_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/clients/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Clients
         * @description Ищет на панелях клиентов, похожих на получателей. Ничего не меняет.
         *
         *     POST, а не GET, ради тела: подсказки для поиска задаются на каждого получателя
         *     отдельно, а список получателей бывает длинным.
         */
        post: operations["suggest_clients_api_campaigns__campaign_id__clients_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/clients/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind Suggestions
         * @description Привязывает всё отмеченное в подборе — по всем получателям сразу.
         */
        post: operations["bind_suggestions_api_campaigns__campaign_id__clients_bind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Campaign
         * @description Создаёт кампанию по образцу прежней: те же получатели и те же привязки.
         *
         *     Конфиги копируются пустыми — их заберёт генерация. Новых людей добавляют обычным
         *     импортом уже в новую кампанию.
         */
        post: operations["clone_campaign_api_campaigns__campaign_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{recipient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recipient */
        delete: operations["delete_recipient_api_recipients__recipient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{recipient_id}/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Configs
         * @description Добавляет получателю ещё конфиги. Генерацию по-прежнему запускает кнопка.
         *
         *     Конфиг создаётся пустым (PENDING) — это же нужно и для привязки: привязать можно
         *     только к существующей строке конфига, а у человека с пятью доступами на панели
         *     строк должно быть пять.
         */
        post: operations["add_configs_api_recipients__recipient_id__configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipients/{recipient_id}/configs/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind New Configs
         * @description Привязывает получателю сразу несколько клиентов панели — по конфигу на каждого.
         */
        post: operations["bind_new_configs_api_recipients__recipient_id__configs_bind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{config_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Config
         * @description Отдаёт файл конфига. Ответ бинарный, без обёртки ApiEnvelope.
         */
        get: operations["download_config_api_configs__config_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{config_id}/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind Config
         * @description Привязывает конфиг к клиенту, заведённому на панели вручную.
         */
        post: operations["bind_config_api_configs__config_id__bind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{config_id}/unbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unbind Config
         * @description Снимает привязку, а лишнюю строку конфига убирает.
         *
         *     Отвечаем получателем целиком, а не конфигом: строки может уже не быть, да и
         *     остальные при этом меняются — фронту всё равно нужен свежий список.
         */
        post: operations["unbind_config_api_configs__config_id__unbind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Config
         * @description Удаляет строку конфига у получателя. Клиент на панели остаётся жить.
         */
        delete: operations["delete_config_api_configs__config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Servers
         * @description Все серверы из конфига, включая выключенные — фронт покажет их неактивными.
         */
        get: operations["list_servers_api_servers_get"];
        put?: never;
        /**
         * Add Server
         * @description Дописывает сервер в `servers.yml`. Доступы приезжают сюда и наружу не возвращаются.
         */
        post: operations["add_server_api_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Server
         * @description Убирает сервер из конфига.
         *
         *     Строки конфигов в прошлых рассылках остаются: это история того, что людям ушло.
         *     Пока они есть, удаление требует `force` — иначе это происходило бы незаметно.
         */
        delete: operations["delete_server_api_servers__server_key__delete"];
        options?: never;
        head?: never;
        /**
         * Update Server
         * @description Включает сервер в рассылки по умолчанию или исключает из них.
         */
        patch: operations["update_server_api_servers__server_key__patch"];
        trace?: never;
    };
    "/api/servers/{server_key}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Server
         * @description Проверяет связь с панелью и читает список клиентов. Ничего не меняет.
         *
         *     POST, а не GET: ручка поднимает SSH-соединение или сессию панели, и кешировать или
         *     предзагружать такое браузеру незачем.
         */
        post: operations["check_server_api_servers__server_key__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers/{server_key}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Panel Clients
         * @description Имена клиентов, которые сейчас есть на панели.
         *
         *     Ходит на живую панель, поэтому отвечает не мгновенно — интерфейс запрашивает это
         *     только когда человек открывает привязку.
         */
        get: operations["list_panel_clients_api_servers__server_key__clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactKind
         * @description Что панель отдаёт получателю.
         * @enum {string}
         */
        ArtifactKind: "file" | "link";
        /**
         * BindConfigIn
         * @description Тело запроса на привязку конфига к клиенту, заведённому на панели вручную.
         */
        BindConfigIn: {
            /** External Name */
            external_name: string;
        };
        /**
         * BindSuggestionItem
         * @description Одна привязка из подбора: кому, на каком сервере и какие клиенты.
         */
        BindSuggestionItem: {
            /** Recipient Id */
            recipient_id: number;
            /** Server Key */
            server_key: string;
            /** Names */
            names: string[];
        };
        /**
         * BindSuggestionsEnvelope
         * @description Обёртка результата массовой привязки.
         */
        BindSuggestionsEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["BindSuggestionsResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * BindSuggestionsIn
         * @description Всё отмеченное в подборе — одним запросом.
         *
         *     Пачкой, а не по одной привязке: каждая проверяет имена по живой панели, и тридцать
         *     получателей превратились бы в десятки заходов по SSH. Здесь панель читается один
         *     раз, а проверки идут разом — в том числе на то, что один клиент не достался двоим.
         */
        BindSuggestionsIn: {
            /** Items */
            items: components["schemas"]["BindSuggestionItem"][];
        };
        /**
         * BindSuggestionsResult
         * @description Сколько привязок легло и к скольким получателям.
         */
        BindSuggestionsResult: {
            /** Bound */
            bound: number;
            /** Recipients */
            recipients: number;
        };
        /**
         * CampaignRead
         * @description Ответ: данные кампании + необязательные счётчики прогресса.
         */
        CampaignRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            status: components["schemas"]["CampaignStatus"];
            /** Servers */
            servers?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Totals */
            totals?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CampaignReadEnvelope
         * @description Обёртка одной кампании.
         */
        CampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["CampaignRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * CampaignStatus
         * @enum {string}
         */
        CampaignStatus: "new" | "in_progress" | "done" | "done_with_errors" | "error";
        /**
         * ClientCandidate
         * @description Клиент панели, похожий на получателя.
         */
        ClientCandidate: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /**
             * Suggested
             * @default false
             */
            suggested: boolean;
            /** Taken By */
            taken_by?: string | null;
            /**
             * Source
             * @default match
             */
            source: string;
        };
        /**
         * CloneCampaign
         * @description Тело запроса на создание кампании по образцу прежней.
         *
         *     Тема и текст по умолчанию берутся у исходной: чаще всего новая рассылка — это та
         *     же самая, но с добавленными людьми.
         */
        CloneCampaign: {
            /** Name */
            name: string;
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
        };
        /**
         * ConfigRead
         * @description Ответ: конфиг получателя с одного сервера, без содержимого файла.
         *
         *     У ссылки подписки содержимое не секретнее самой ссылки, поэтому `link` отдаём
         *     как есть — фронт показывает её кнопкой «скопировать».
         */
        ConfigRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Panel Name */
            panel_name: string;
            /** Seq */
            seq: number;
            /** External Name */
            external_name?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /** Server Key */
            server_key: string;
            kind: components["schemas"]["ArtifactKind"];
            status: components["schemas"]["ConfigStatus"];
            /** Filename */
            filename?: string | null;
            /** Link */
            link?: string | null;
            /**
             * Size
             * @default 0
             */
            size: number;
            /** Error */
            error?: string | null;
        };
        /**
         * ConfigReadEnvelope
         * @description Обёртка одного конфига (привязка к клиенту панели).
         */
        ConfigReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ConfigRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ConfigStatus
         * @enum {string}
         */
        ConfigStatus: "pending" | "queued" | "generating" | "ready" | "failed";
        /**
         * ConfigsAdd
         * @description Тело запроса на добавление получателю ещё конфигов.
         *
         *     `servers` — на каких серверах добавить; пусто означает «на всех включённых».
         *     Список нужен как раз для несимметричного случая: человеку нужно пять доступов на
         *     одном сервере и по одному на остальных — на панели это пять отдельных клиентов.
         */
        ConfigsAdd: {
            /** Servers */
            servers?: string[] | null;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /**
         * ConfigsBind
         * @description Тело запроса на привязку сразу нескольких клиентов панели к одному получателю.
         *
         *     Под каждое имя заводится **свой** конфиг: у человека столько доступов, сколько
         *     устройств, и привязка второго клиента не должна затирать первый.
         */
        ConfigsBind: {
            /** Server Key */
            server_key: string;
            /** Names */
            names: string[];
        };
        /**
         * CreateCampaign
         * @description Тело запроса на создание кампании.
         */
        CreateCampaign: {
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Servers */
            servers?: string[];
        };
        /**
         * GenerateConfigsIn
         * @description Тело запроса на генерацию: на каких серверах.
         *
         *     Пустой список (или отсутствующее тело) — все серверы рассылки, то есть кнопка
         *     «Сгенерировать все».
         */
        GenerateConfigsIn: {
            /**
             * Servers
             * @default []
             */
            servers: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportGroup
         * @description Одно письмо: получатель, его базовое имя и сколько конфигов ему нужно.
         *
         *     `existing_client_name` заполняется, если получатель в кампании уже есть: имя
         *     менять не будем, и в предпросмотре видно, какое останется.
         */
        ImportGroup: {
            /** Email */
            email: string;
            /** Client Name */
            client_name: string;
            /** Existing Client Name */
            existing_client_name?: string | null;
            /**
             * Is Existing
             * @default false
             */
            is_existing: boolean;
            /**
             * Count
             * @default 1
             */
            count: number;
            /**
             * Existing Count
             * @default 0
             */
            existing_count: number;
            /**
             * New Configs
             * @default 0
             */
            new_configs: number;
            /**
             * Servers
             * @default []
             */
            servers: string[];
            /**
             * New Names
             * @default []
             */
            new_names: string[];
            /**
             * Bindings
             * @default {}
             */
            bindings: {
                [key: string]: string;
            };
        };
        /**
         * ImportPreview
         * @description Предпросмотр импорта: что получится, если сохранить.
         */
        ImportPreview: {
            /** Groups */
            groups: components["schemas"]["ImportGroup"][];
            /**
             * Problems
             * @default []
             */
            problems: components["schemas"]["ImportRowProblem"][];
            /** Total Rows */
            total_rows: number;
            /** Total Recipients */
            total_recipients: number;
            /** Total Configs */
            total_configs: number;
        };
        /**
         * ImportPreviewEnvelope
         * @description Обёртка предпросмотра импорта получателей.
         */
        ImportPreviewEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ImportPreview"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ImportResult
         * @description Итог импорта.
         */
        ImportResult: {
            /** Created Recipients */
            created_recipients: number;
            /** Updated Recipients */
            updated_recipients: number;
            /** Created Configs */
            created_configs: number;
            /**
             * Problems
             * @default []
             */
            problems: components["schemas"]["ImportRowProblem"][];
        };
        /**
         * ImportResultEnvelope
         * @description Обёртка результата импорта получателей.
         */
        ImportResultEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ImportResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ImportRowProblem
         * @description Строка, которую не удалось разобрать.
         */
        ImportRowProblem: {
            /** Line */
            line: number;
            /** Raw */
            raw: string;
            /** Reason */
            reason: string;
        };
        /**
         * ListCampaignReadEnvelope
         * @description Обёртка списка кампаний.
         */
        ListCampaignReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["CampaignRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListPanelClientsEnvelope
         * @description Обёртка списка имён клиентов, живущих на панели сервера.
         */
        ListPanelClientsEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListRecipientReadEnvelope
         * @description Обёртка списка получателей.
         */
        ListRecipientReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["RecipientRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ListServerReadEnvelope
         * @description Обёртка списка настроенных VPN-серверов.
         */
        ListServerReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            /** Result */
            result?: components["schemas"]["ServerRead"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * MessageOut
         * @description Универсальный ответ операции (старт/стоп/импорт).
         */
        MessageOut: {
            /** Detail */
            detail: string;
            /** Campaign Id */
            campaign_id: number;
        };
        /**
         * MessageOutEnvelope
         * @description Обёртка служебного сообщения (старт/стоп).
         */
        MessageOutEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["MessageOut"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * PanelAuth
         * @description Доступ к API панели.
         *
         *     У 3x-ui это Bearer-токен из Settings → Security → API Token (на старых версиях
         *     токена нет — там логин с паролем и cookie-сессия). У wg-easy v15 — логин и пароль
         *     от веб-морды через Basic Auth. У AmneziaWG — логин и пароль от панели.
         */
        PanelAuth: {
            /**
             * Token
             * @default
             */
            token: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /**
         * PanelKind
         * @description Тип панели на сервере — определяет, каким адаптером с ним говорить.
         * @enum {string}
         */
        PanelKind: "amnezia" | "3x-ui" | "wg-easy" | "fake";
        /**
         * RecipientCreate
         * @description Тело запроса на добавление одного получателя.
         *
         *     `client_name` — базовое имя клиента, `count` — сколько конфигов ему нужно. Имена
         *     получаются нумерацией (`alice` + 3 → `alice1`, `alice2`, `alice3`), и каждое
         *     заводится на каждом включённом сервере.
         */
        RecipientCreate: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Client Name */
            client_name: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /**
         * RecipientRead
         * @description Ответ: получатель со статусом отправки и списком конфигов.
         */
        RecipientRead: {
            /** Id */
            id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Client Name */
            client_name: string;
            /** Config Count */
            config_count: number;
            status: components["schemas"]["RecipientStatus"];
            /** Error */
            error?: string | null;
            /** Sent At */
            sent_at?: string | null;
            /**
             * Configs
             * @default []
             */
            configs: components["schemas"]["ConfigRead"][];
        };
        /**
         * RecipientReadEnvelope
         * @description Обёртка одного получателя.
         */
        RecipientReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["RecipientRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * RecipientStatus
         * @enum {string}
         */
        RecipientStatus: "pending" | "sent" | "failed";
        /**
         * RecipientSuggestion
         * @description Подбор для одного получателя по всем серверам.
         */
        RecipientSuggestion: {
            /** Recipient Id */
            recipient_id: number;
            /** Email */
            email: string;
            /** Client Name */
            client_name: string;
            /**
             * Servers
             * @default []
             */
            servers: components["schemas"]["ServerSuggestion"][];
        };
        /**
         * RecipientsBulk
         * @description Массовое добавление получателей.
         */
        RecipientsBulk: {
            /** Items */
            items: components["schemas"]["RecipientCreate"][];
        };
        /**
         * RecipientsImportText
         * @description Тело запроса: вставленный из таблицы текст (две колонки через таб).
         */
        RecipientsImportText: {
            /** Text */
            text: string;
        };
        /**
         * ServerCheck
         * @description Результат проверки доступности панели. Ничего на сервере не меняет.
         */
        ServerCheck: {
            /** Key */
            key: string;
            /** Ok */
            ok: boolean;
            /** Clients */
            clients?: number | null;
            /**
             * Sample
             * @default []
             */
            sample: string[];
            /**
             * Protocol
             * @default
             */
            protocol: string;
            /**
             * Subscription
             * @default
             */
            subscription: string;
            /** Client Found */
            client_found?: boolean | null;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Hint
             * @default
             */
            hint: string;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
        };
        /**
         * ServerCheckEnvelope
         * @description Обёртка результата проверки доступности панели.
         */
        ServerCheckEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ServerCheck"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ServerCreate
         * @description Тело запроса на добавление сервера.
         *
         *     Ровно тот же набор полей, что и в `servers.yml`: проверки («при transport=ssh нужен
         *     блок ssh», «для 3x-ui нужен inbound_ids») уже написаны валидатором модели, и
         *     дублировать их отдельной схемой значило бы разойтись с файлом при первой же правке.
         */
        ServerCreate: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            panel: components["schemas"]["PanelKind"];
            transport: components["schemas"]["TransportKind"];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Base Url
             * @default http://127.0.0.1:8080
             */
            base_url: string;
            ssh?: components["schemas"]["SshConfig"] | null;
            auth?: components["schemas"]["PanelAuth"];
            /** Inbound Ids */
            inbound_ids?: number[];
            /**
             * Flow
             * @default
             */
            flow: string;
            /**
             * Sub Base
             * @default
             */
            sub_base: string;
            /** Name Suffixes */
            name_suffixes?: string[];
            /**
             * Panel Server Id
             * @default
             */
            panel_server_id: string;
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            artifact?: components["schemas"]["ArtifactKind"] | null;
        };
        /**
         * ServerDeleted
         * @description Ответ на удаление сервера из конфига.
         */
        ServerDeleted: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
        };
        /**
         * ServerDeletedEnvelope
         * @description Обёртка результата удаления сервера из конфига.
         */
        ServerDeletedEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ServerDeleted"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ServerRead
         * @description Ответ: один настроенный сервер.
         */
        ServerRead: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            panel: components["schemas"]["PanelKind"];
            transport: components["schemas"]["TransportKind"];
            artifact: components["schemas"]["ArtifactKind"];
            /** Enabled */
            enabled: boolean;
            /** Where */
            where: string;
            /**
             * Configs
             * @default 0
             */
            configs: number;
            /**
             * Unfinished
             * @default 0
             */
            unfinished: number;
        };
        /**
         * ServerReadEnvelope
         * @description Обёртка одного VPN-сервера.
         */
        ServerReadEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["ServerRead"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ServerSuggestion
         * @description Что нашлось для получателя на одном сервере.
         *
         *     `error` вместо кандидатов — панель не ответила. Это не повод валить весь подбор:
         *     остальные серверы всё равно полезны, а привязать к недоступной панели всё равно
         *     нельзя.
         */
        ServerSuggestion: {
            /** Server Key */
            server_key: string;
            /** Server Title */
            server_title: string;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["ClientCandidate"][];
            /** Error */
            error?: string | null;
        };
        /**
         * SshConfig
         * @description Как подключаться к серверу по SSH.
         *
         *     `host` — либо алиас из `~/.ssh/config`, либо обычное имя хоста. Всё, что задано
         *     здесь явно, перекрывает найденное в `~/.ssh/config`.
         */
        SshConfig: {
            /** Host */
            host: string;
            /**
             * Use Ssh Config
             * @default true
             */
            use_ssh_config: boolean;
            /**
             * Config Path
             * @default ~/.ssh/config
             */
            config_path: string;
            /**
             * User
             * @default
             */
            user: string;
            /** Port */
            port?: number | null;
            /**
             * Key File
             * @default
             */
            key_file: string;
            /**
             * Key Passphrase
             * @default
             */
            key_passphrase: string;
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
        };
        /**
         * SuggestClientsIn
         * @description Тело запроса на подбор.
         *
         *     `recipient_ids` пустой — подбираем всей кампании: панели опрашиваются один раз на
         *     запрос, поэтому разом это дешевле, чем по одному получателю.
         *
         *     `hints` — подсказка для поиска, ключ строкой (id получателя), значение свободное:
         *     фамилия или кусок имени с панели. Нужна, когда ни почта, ни базовое имя о человеке
         *     ничего не говорят — `kboyko2022` против `boykokr` угадывается, а вот `user17` нет.
         */
        SuggestClientsIn: {
            /** Recipient Ids */
            recipient_ids?: number[] | null;
            /** Hints */
            hints?: {
                [key: string]: string;
            };
        };
        /** SuggestResult */
        SuggestResult: {
            /**
             * Recipients
             * @default []
             */
            recipients: components["schemas"]["RecipientSuggestion"][];
        };
        /**
         * SuggestResultEnvelope
         * @description Обёртка подбора клиентов панели.
         */
        SuggestResultEnvelope: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["SuggestResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * TransportKind
         * @description Как достучаться до API панели.
         * @enum {string}
         */
        TransportKind: "ssh" | "direct";
        /**
         * UpdateCampaign
         * @description Правка кампании до запуска: меняется только переданное.
         */
        UpdateCampaign: {
            /** Name */
            name?: string | null;
            /** Subject */
            subject?: string | null;
            /** Body */
            body?: string | null;
        };
        /**
         * UpdateServer
         * @description Тело запроса на включение сервера в рассылки по умолчанию или исключение из них.
         */
        UpdateServer: {
            /** Enabled */
            enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_api_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCampaignReadEnvelope"];
                };
            };
        };
    };
    create_campaign_api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaign"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_api_campaigns__campaign_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampaign"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipients_api_campaigns__campaign_id__recipients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_recipients_api_campaigns__campaign_id__recipients_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsBulk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_recipients_import_api_campaigns__campaign_id__recipients_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsImportText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_recipients_api_campaigns__campaign_id__recipients_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientsImportText"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_configs_api_campaigns__campaign_id__configs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateConfigsIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_campaign_api_campaigns__campaign_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_failed_api_campaigns__campaign_id__retry_failed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_campaign_api_campaigns__campaign_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_clients_api_campaigns__campaign_id__clients_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SuggestClientsIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResultEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_suggestions_api_campaigns__campaign_id__clients_bind_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindSuggestionsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindSuggestionsEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_campaign_api_campaigns__campaign_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneCampaign"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipient_api_recipients__recipient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_configs_api_recipients__recipient_id__configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigsAdd"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_new_configs_api_recipients__recipient_id__configs_bind_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigsBind"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_config_api_configs__config_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_config_api_configs__config_id__bind_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unbind_config_api_configs__config_id__unbind_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_config_api_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_servers_api_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListServerReadEnvelope"];
                };
            };
        };
    };
    add_server_api_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_api_servers__server_key__delete: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                server_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerDeletedEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_server_api_servers__server_key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerReadEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_server_api_servers__server_key__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerCheckEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_panel_clients_api_servers__server_key__clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPanelClientsEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
